language: java
jdk:
   - oraclejdk8
services:
  - mysql
before_install:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -u root --password="root" -e 'CREATE DATABASE LearnersManagementSystem;'